language: ruby
script: echo "FO0"
rvm:
  - 2.3.1
notifications:
  email: false
  webhooks:
    urls:
      - http://requestb.in/16znuui1
    on_success: always
    on_failure: always
    on_start: true
